const fs = require('fs');
const lines = fs.readFileSync('src/components/Dashboard.tsx', 'utf8').split('\n');
const newLines = lines.slice(0, 539);
newLines.push(
    '                                            fillOpacity={1}',
    '                                            fill="url(#colorDashboard)"',
    '                                        />',
    '                                    </AreaChart>',
    '                                </ResponsiveContainer>',
    '                            </div>',
    '                        </div>',
    '                    </div>',
    '',
    '                    <div className="w-full bg-white rounded-[2rem] shadow-sm border border-slate-100 p-8 flex flex-col md:flex-row items-center justify-between gap-10">',
    '                        <div className="flex flex-col gap-5 w-full flex-1">',
    '                            <div className="bg-slate-50 rounded-[1.5rem] p-6 px-8 flex items-center justify-between border border-slate-100 shadow-sm hover:shadow-md transition-all">',
    '                                <div className="flex items-center gap-3">',
    '                                    <div className="h-4 w-4 rounded bg-red-500 flex items-center justify-center">',
    '                                        <div className="h-1.5 w-1.5 bg-white rounded-full" />',
    '                                    </div>',
    '                                    <span className="text-[11px] font-black text-slate-900 tracking-widest">M-PESA</span>',
    '                                </div>',
    '                                ',
    '                                <div className="flex items-center gap-6">',
    '                                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{mpesaCount} Vendas</span>',
    '                                </div>',
    '                            </div>',
    '                            <div className="bg-slate-50 rounded-[1.5rem] p-6 px-8 flex items-center justify-between border border-slate-100 shadow-sm hover:shadow-md transition-all">',
    '                                <div className="flex items-center gap-3">',
    '                                    <div className="h-4 w-4 rounded bg-orange-500 flex items-center justify-center">',
    '                                        <div className="h-1.5 w-1.5 bg-white rounded-full" />',
    '                                    </div>',
    '                                    <span className="text-[11px] font-black text-slate-900 tracking-widest">E-MOLA</span>',
    '                                </div>',
    '                                <div className="flex items-center gap-6">',
    '                                    <span className="text-xl font-black text-violet-600">{emolaPercent}%</span>',
    '                                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{emolaCount} Vendas</span>',
    '                                    <div className="flex items-center gap-2 bg-emerald-50 text-emerald-600 px-2 py-1 rounded-full">',
    '                                        <span className="text-[9px] font-black uppercase tracking-widest">Conversão</span>',
    '                                        <span className="text-sm font-black">{conversionRate}%</span>',
    '                                    </div>',
    '                                </div>',
    '                            </div>',
    '                        </div>',
    '',
    '                        <div className="flex flex-col items-center justify-center order-1 md:order-2 md:pl-16 md:border-l border-slate-100 dark:border-white/5 md:w-64 shrink-0">',
    '                            <span className="text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Total Vendas</span>',
    '                            <span className="text-6xl font-black text-slate-900 tracking-tighter mb-4">{totalApprovedCount}</span>',
    '                        </div>',
    '                    </div>',
    '                </div>',
    '            </div>',
    '        </div>',
    '    );',
    '}',
    'export default Dashboard;'
);
fs.writeFileSync('src/components/Dashboard.tsx', newLines.join('\n'));
console.log('Fixed Dashboard.tsx');
